// Mock data for Blinko dashboard experience

export const MOCK_STATS = [
  {
    id: "total-views",
    label: "Total Views",
    value: "12,480",
    change: "+18.2%",
    isPositive: true,
    timeframe: "vs last 30 days",
    iconName: "Eye",
  },
  {
    id: "total-clicks",
    label: "Total Clicks",
    value: "3,842",
    change: "+24.5%",
    isPositive: true,
    timeframe: "vs last 30 days",
    iconName: "MousePointerClick",
  },
  {
    id: "conversion-rate",
    label: "Conversion Rate",
    value: "30.7%",
    change: "+4.1%",
    isPositive: true,
    timeframe: "vs last 30 days",
    iconName: "TrendingUp",
  },
  {
    id: "profile-visits",
    label: "Profile Visits",
    value: "1,240",
    change: "-2.3%",
    isPositive: false,
    timeframe: "vs last 30 days",
    iconName: "Users",
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "act-1",
    user: "Someone",
    action: "clicked GitHub link",
    time: "2 mins ago",
    details: "Referrer: GitHub profile",
    iconName: "Github",
  },
  {
    id: "act-2",
    user: "Anonymous user",
    action: "viewed Portfolio gallery",
    time: "15 mins ago",
    details: "IP Country: United States",
    iconName: "Eye",
  },
  {
    id: "act-3",
    user: "Inquirer",
    action: "opened Contact form",
    time: "1 hour ago",
    details: "Referrer: Direct",
    iconName: "Mail",
  },
  {
    id: "act-4",
    user: "Recruiter",
    action: "downloaded Resume PDF",
    time: "3 hours ago",
    details: "Referrer: LinkedIn",
    iconName: "Download",
  },
  {
    id: "act-5",
    user: "Someone",
    action: "clicked LinkedIn link",
    time: "5 hours ago",
    details: "IP Country: Germany",
    iconName: "Linkedin",
  },
];

export const MOCK_LINKS = [
  {
    id: "link-1",
    title: "GitHub Profile",
    url: "https://github.com/lenny",
    status: "active",
    clicks: 1450,
    iconName: "Github",
  },
  {
    id: "link-2",
    title: "My Portfolio",
    url: "https://lenny.dev",
    status: "active",
    clicks: 980,
    iconName: "ExternalLink",
  },
  {
    id: "link-3",
    title: "LinkedIn Profile",
    url: "https://linkedin.com/in/lenny",
    status: "active",
    clicks: 720,
    iconName: "Linkedin",
  },
  {
    id: "link-4",
    title: "My Resume",
    url: "https://lenny.dev/resume.pdf",
    status: "inactive",
    clicks: 34,
    iconName: "FileText",
  },
];

export const MOCK_THEMES = [
  {
    id: "minimal",
    name: "Minimal",
    bgClass: "bg-zinc-950",
    previewBg: "#09090b",
    previewText: "#fafafa",
    previewCard: "bg-zinc-900 border-zinc-800",
    accentColor: "#f4f4f5",
    fontFamily: "font-sans",
    buttonStyle: "rounded-md",
  },
  {
    id: "creator",
    name: "Creator",
    bgClass: "bg-[#0A0518]",
    previewBg: "#0a0518",
    previewText: "#f5f3ff",
    previewCard: "bg-[#130B2D] border-[#2E185D]",
    accentColor: "#a78bfa",
    fontFamily: "font-sans",
    buttonStyle: "rounded-full",
  },
  {
    id: "developer",
    name: "Developer Theme",
    bgClass: "bg-black border border-emerald-500/20",
    previewBg: "#000000",
    previewText: "#10b981",
    previewCard: "bg-zinc-900/50 border-emerald-500/10",
    accentColor: "#10b981",
    fontFamily: "font-mono",
    buttonStyle: "rounded-none",
  },
  {
    id: "artist",
    name: "Artist",
    bgClass: "bg-[#1A0B0B]",
    previewBg: "#1a0b0b",
    previewText: "#fee2e2",
    previewCard: "bg-[#2D1616] border-[#4A2323]",
    accentColor: "#f87171",
    fontFamily: "font-serif",
    buttonStyle: "rounded-2xl",
  },
  {
    id: "startup",
    name: "Startup",
    bgClass: "bg-[#0F172A]",
    previewBg: "#0f172a",
    previewText: "#f8fafc",
    previewCard: "bg-[#1E293B] border-[#334155]",
    accentColor: "#38bdf8",
    fontFamily: "font-sans",
    buttonStyle: "rounded-lg",
  },
  {
    id: "dark-pro",
    name: "Dark Pro",
    bgClass: "bg-[#050505]",
    previewBg: "#050505",
    previewText: "#ffffff",
    previewCard: "bg-[#111111] border-[#222222]",
    accentColor: "#7c3aed",
    fontFamily: "font-sans",
    buttonStyle: "rounded-md",
  },
];

export const MOCK_PLANS = {
  current: {
    name: "Free",
    metrics: [
      { name: "Pages Created", current: 1, limit: 1, percent: 100 },
      { name: "Monthly Views", current: 1240, limit: 5000, percent: 24.8 },
      { name: "Links Used", current: 4, limit: 5, percent: 80 },
    ],
  },
  pricing: [
    {
      name: "Free",
      price: "$0",
      period: "forever",
      description: "Perfect for personal side projects & social links.",
      features: [
        "1 Active Link-in-Bio Page",
        "Up to 5 Links",
        "Standard Templates",
        "Basic Link Analytics",
        "Blinko Branding",
      ],
      isPopular: false,
      cta: "Current Plan",
    },
    {
      name: "Pro",
      price: "$5",
      period: "month",
      description: "For professionals and content creators growing their brand.",
      features: [
        "Unlimited Pages & Mini Sites",
        "Unlimited Custom Links",
        "Premium Visual Themes",
        "Custom Domain Support",
        "Advanced SEO & Bio Analytics",
        "AI Auto Bio & Content Writer",
        "Priority Customer Support",
        "Remove Blinko Branding",
      ],
      isPopular: true,
      cta: "Upgrade to Pro",
    },
  ],
  history: [
    {
      id: "inv-001",
      date: "Jun 1, 2026",
      amount: "$0.00",
      status: "Paid",
      invoice: "INV-2026-001",
    },
    {
      id: "inv-002",
      date: "May 1, 2026",
      amount: "$0.00",
      status: "Paid",
      invoice: "INV-2026-002",
    },
  ],
};

export const MOCK_AI_SUGGESTIONS = {
  student: {
    theme: "Developer Theme",
    layout: "Portfolio First",
    sections: [
      { id: "sec-1", title: "Portfolio Section", type: "portfolio", details: "Showcase of recent student coding projects and hackathons." },
      { id: "sec-2", title: "Resume Download", type: "resume", details: "Quick PDF download for internship recruiters." },
      { id: "sec-3", title: "GitHub & LinkedIn Links", type: "socials", details: "Direct pathways to active profile repositories." },
      { id: "sec-4", title: "Contact Me form", type: "contact", details: "Simple inline message sender." },
    ],
  },
  designer: {
    theme: "Minimal",
    layout: "Visual Gallery First",
    sections: [
      { id: "sec-1", title: "Visual Showcase", type: "portfolio", details: "Grid showcasing high-resolution design mockups." },
      { id: "sec-2", title: "Client Inquiry Form", type: "contact", details: "Form to gather budget and timeline details from prospective leads." },
      { id: "sec-3", title: "Dribbble & Instagram links", type: "socials", details: "Links to design platforms showing social proof." },
      { id: "sec-4", title: "Latest Case Study", type: "external-link", details: "Case study walk-through of the latest UX overhaul." },
    ],
  },
  youtuber: {
    theme: "Creator",
    layout: "Video Highlight First",
    sections: [
      { id: "sec-1", title: "Latest Tutorial Video", type: "video", details: "Embedded video link pointing to the newest YouTube content." },
      { id: "sec-2", title: "Sponsorship & Collabs Form", type: "contact", details: "Streamlined workflow for brand sponsor communications." },
      { id: "sec-3", title: "Twitch & Twitter profiles", type: "socials", details: "Dynamic links to social channels for community engagement." },
      { id: "sec-4", title: "Merchandise Store Link", type: "store", details: "E-commerce redirection to buy hoodies and merchandise." },
    ],
  },
};
